# -*- coding: utf-8 -*-
"""stylecheck

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpeCbd2xEKMXvbAydddOzylGM7ZfC8Mh
"""

!pip install -r requirements.txt

#!git version
!git init --initial-branch=main

!git config user.email "5698694+claireporter@users.noreply.github.com"
!git config user.name "claireporter"

!git clone https://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@github.com/claireporter/stylecheck.git

!mkdir -p style_check/data

# Commented out IPython magic to ensure Python compatibility.
# %cd style_check/

!echo "# Some dummy text" >> new.md

!git status

!rm -r /content/style_check/new.md

!git add .

!git commit -m "First commit"

!git remote add origin https://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@github.com/claireporter/stylecheck.git

!git push -u origin main

!git remote -v

!git branch -M main

!git push -u origin main

!git remote remove origin

!git remote add origin https://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@github.com/claireporter/stylecheck.git

!git push -u origin main

!git pull -u origin main

!git push -u origin main

!git pull origin main --rebase

!git push -u origin main

!git remote add origin https://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@github.com/claireporter/stylecheck.git

!git add .

!git commit -m "Add first files"

!git push -u origin main

!git add .
!git commit -m "re-structure code"

!jupyter nbconvert --to script notebooks/checkarticle.ipynb --output scripts/checkarticle.py